### ISSUE TITLE
Back arrow on asset page not functioning

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1092] opened 2023-07-13 12:02 UTC
Back arrow on the asset page (only present in mobile view) only navigates back after 3 clicks or so when coming from the maps page.

This is due to `window.history.back()` being used in `or-asset-viewer`, which is not working in practice.
The URL frequently changes on the asset page, making it necessary to click multiple times.

Concerns to discuss;
- How should we support "navigating back', since there is no page history state in our app?
- Why is navigation present in `or-asset-viewer` in the first place?

**Comment by DonWillems** [comment] 2023-07-14 11:45
Duplicate of #933 . Closing and adding the content as comment in that issue.

**Closed by DonWillems** 2023-07-14 11:45 UTC
Labels: bug
