### ISSUE TITLE
Data export page V1

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#405] opened 2021-04-19 15:08 UTC
**User requirements**

[See specification](https://docs.google.com/document/d/1LZOKCIng-_mssSwULkTBFgeaR5Okjo6I1gM3VEAqHvE/edit#heading=h.k2kvsus5xs9a)

As a user I want to export raw data of selected asset attributes for a specific time range as a .csv so that I can use it for further data analysis

- [x] Time range select
- [x] List of selected asset attributes
- [x] Selection of time and attributes is stored in local storage for easy repeat/forgiving when navigating away.
- [x] Asset attributes selection modal with multiselect (only attributes that have the 'STORE_DATA_POINTS' configuration item true should be shown. If no attribute of an asset has that show explanation text)
- [x] Export button that generates csv, with cancel option.
- [x] Page only visible to users with read data rights
- [ ] Event is logged and can be found on the logs page.

**Technical requirements**
- [x] Call this page `page-export` and add to defaults in `manager` app (need route provider etc. also - see other pages)

**Comment by Miggets7** [comment] 2021-06-02 06:22
Pushed an update to the main branch. Added export endpoint in AssetDatapointResource. The implementation(AssetDatapointResourceImpl)  expects that the query param `attributeRefsString` is a JSON. For e.g. `[{"id":"random_id", "name": "attribute_name"}, ...]`

**Comment by vlichtenberg** [comment] 2021-06-14 15:36
Hi,
Just pulled and merged master back into my branch, but the manager is still throwing a 500 when posting the following request:
`attributeRefsString: [{"id":"3bSQvcQK9n5IA1leSVbz6b","name":"carbonImport"},{"id":"3bSQvcQK9n5IA1leSVbz6b","name":"efficiencyImport"}]
fromTimestamp: 1623684496063
toTimestamp: 1623684496063`

The error (it looks like it wants a content argument, but it doesn't say so according to spec - what should I put?):
`Request failed with HTTP error status: 500 Internal Server Error

java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4757)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3515)
	at org.openremote.manager.datapoint.AssetDatapointResourceImpl.getDatapointExport(AssetDatapointResourceImpl.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:338)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.openremote.container.security.CORSFilter.doFilter(CORSFilter.java:137)
	at org.openremote.container.web.file.HttpFilter.doFilter(HttpFilter.java:108)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.openremote.container.security.IdentityService$1$1.handleRequest(IdentityService.java:100)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by richturner** [comment] 2021-06-15 08:36
`AssetDatapointResourceClient` `getDatapointExport` function is a `GET` request with queryParams `attributeRefs` is the name of the query param which should be stringified JSON of `AttributeRef[]`

**Comment by Miggets7** [comment] 2021-06-15 08:43
Was just about to answer, but @richturner was sooner. 

Indeed it's a `GET` request, so all of the parameters of `export` should be in the query string.
For e.g.
`?attributeRefs=[{"id":"asset_id", "name": "attribute_name"}, ...]&fromTimestamp=value&toTimestamp=value`

**Comment by vlichtenberg** [comment] 2021-06-17 12:42
That explains a lot. Will wrap it up either late tonight or first thing tomorrow. Thanks!

**Comment by pierrekil** [comment] 2021-06-21 06:53
- [ ] At initial entry of export page, I don't see an '+ attribute' button. It only appears when I select 'clear', although I have not selected any attributes yet.
![Screenshot 2021-06-21 at 08 46 22](https://user-images.githubusercontent.com/11444149/122718939-d1ea6600-d26d-11eb-8570-edef65a558a3.png)
- [ ] When an attribute and a period are selected, export (Macbook) doesn't work
- [ ] All labels change language when changing language, except 'Add Asset Attribute', it needs a page refresh first.

**Comment by vlichtenberg** [comment] 2021-06-25 13:24
Hi @Miggets7, could you maybe check the second finding in @pierrekil 's comment above? I can't reproduce this when I'm building locally (ie it just works), and also I don't have a Macbook (though I don't think believe that's the issue since Don reproduced this on Staging using a Windows machine). Gives a 500 error on what I'd think is a valid request from the front-end.

**Comment by pierrekil** [comment] 2021-06-28 08:48
- [ ] Export as .zip

**Comment by richturner** [comment] 2021-06-28 16:02
I have added the `responseType` `blob` to the `XMLHttpRequest` generated by the export request so hopefully this will prevent the corruption issue.

**Closed** 2021-07-02 13:00 UTC
Labels: Feature

**Comment by pierrekil** [comment] 2021-07-02 13:03
closed, replaced by #451
