### ISSUE TITLE
Console: provider for offline/online events

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1091] opened 2023-07-13 09:17 UTC
**Topic:**
As a user I want to be directly notified if I'm offline/disconnected from the manager.

**Problem:**
Currently we listen to keycloak token validity to decide on whether a user is offline or not.
In the future we could listen for a ping/pong in a websocket connection, but it is still not 'instant' enough.

**How to solve:**
So, we would like to add a provider that notifies the Manager UI when 'went offline' / 'went online' events occur.
This way we can customize what is happening in the frontend, such as reconnecting to keycloak or showing a snackbar message.

**Comment by DonWillems** [comment] 2024-12-05 10:24
Duplicate of #1234

**Closed by DonWillems** 2024-12-05 10:24 UTC
Labels: Enhancement, Console
