### ISSUE TITLE
Realm and Auto provision pages are empty

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1021] opened 2023-03-30 19:31 UTC
<img width="1325" alt="Screenshot 2023-03-30 at 21 29 53" src="https://user-images.githubusercontent.com/11444149/228944282-511ecad5-4c47-492d-8abb-6b29e1f2e899.png">

**Comment by richturner** [comment] 2023-03-30 20:24
This looks to be caused by a regression in hibernate:

https://hibernate.atlassian.net/browse/HHH-16191

It has been fixed in their latest release candidate but I cannot upgrade to that as there is a breaking change which affects another dependency we use called `hibernate-types`

**Closed** 2023-03-30 21:12 UTC
Labels: bug
