### ISSUE TITLE
GET /asset/datapoint/{assetId}/attribute/{attributeName} - 500 Internal Server Error.

### ISSUE THREAD

**Issue by DasAuryn** [openremote/openremote#1001] opened 2023-03-15 12:03 UTC
Feedback from backend:

```
openremote-manager-1     | 2023-03-15 12:53:20.538  INFO    [WebService task-5] emote.container.web.WebServiceExceptions : Web service exception in 'RESTEasy Dispatch' for 'GET http://localhost/asset/datapoint/4tuvOqeBh02Ga42bguqXGq/attribute/efficiencyExport', root cause: java.lang.NullPointerException: Cannot invoke "org.openremote.model.datapoint.DatapointInterval.ordinal()" because "this.val$datapointInterval" is null
openremote-proxy-1       | 15/Mar/2023:11:53:17 +0000 https~ 172.20.0.1:52266 manager 0/0/0/24/24 "GET /api/master/asset/datapoint/4tuvOqeBh02Ga42bguqXGq/attribute/efficiencyExport HTTP/1.1" 500 2/2/1/1/0 0/0
```

@MartinaeyNL @richturner @DonWillems

**Comment by MartinaeyNL** [comment] 2023-03-15 12:22
Hi! Thanks for making an issue in the first place!

I'm guessing this bug occured after updating OpenRemote?
Can you give context on whether this is an error within OpenRemote or a custom application that uses our HTTP API?

We recently made an update to the API that changes the spec for `/asset/datapoint/{assetId}/attribute/{attributeName}`
It now uses `POST` instead of `GET`, and should include a body with an AssetDatapointQuery object.

```java
    @POST
    @Path("{assetId}/attribute/{attributeName}")
    @Consumes(APPLICATION_JSON)
    @Produces(APPLICATION_JSON)
    @RolesAllowed({Constants.READ_ASSETS_ROLE})
    ValueDatapoint<?>[] getDatapoints(@BeanParam RequestParams requestParams,
                                      @PathParam("assetId") String assetId,
                                      @PathParam("attributeName") String attributeName,
                                      AssetDatapointQuery query);
```

The new AssetDatapointQuery is a base class object that includes timestamps, but can be extended to anything.
Currently all implementations of it are located in the `org.openremote.model.datapoint.query` package (and directory).

You can also check our swagger documentation for more info on the updated spec.

**Comment by DasAuryn** [comment] 2023-03-15 12:36
Hi Martin,

this issue is mentioned by a forum user:

you can reproduce this issue in swagger. 

I guess the forum user has the newest manager image. In my case my image is, i guess 3 months old, so this issue has been undetected a longer time.

**Comment by MartinaeyNL** [comment] 2023-03-15 12:50
Oh I wasn't aware. Thanks for sharing!
I'll reply on the forum as well.

I am able to indeed reproduce the issue on `demo.openremote.app/swagger`.
The update I was talking about was merged to master last week, but hasn't been deployed on demo yet.
Our internal staging environment does not have the issue anymore, but that is of course expected since the spec got changed.

So updating the manager should work, but be aware of the endpoint spec change as mentioned above. (if you're interacting with the HTTP API manually)

**Comment by richturner** [comment] 2023-03-23 16:17
I have also seen this error on the latest code; there was a concurrency issue with event subscriptions which sould be solved once #1529 is merged.

**Closed by richturner** 2023-03-23 16:17 UTC
Labels: bug

**Comment by rmwiseman** [comment] 2023-03-30 09:35
When will the merge happen?  And when it does, will there be a guide for how to migrate to the new API?

**Comment by richturner** [comment] 2023-03-30 17:48
The concurrency fix is now merged and there are no changes to the API, please let us know if you still experience issues

**Comment by rmwiseman** [comment] 2023-03-31 14:48
Thanks @richturner, but above, @MartinaeyNL said:

> We recently made an update to the API that changes the spec for /asset/datapoint/{assetId}/attribute/{attributeName}
> It now uses POST instead of GET, and should include a body with an AssetDatapointQuery object.

Is that not in this update?

**Comment by MartinaeyNL** [comment] 2023-03-31 15:18
That HTTP API change already has been merged earlier. (in #932)

Regarding migration to the new HTP API spec; it should not require any effort if you're only running the OpenRemote stack.
However if you're having a seperate app that interacts with our HTTP API manually, it does require manual attention.
I described the changes in my comment above, and the Swagger documentation can help you as well with this.

**Comment by rmwiseman** [comment] 2023-04-01 07:19
Thanks @MartinaeyNL.  I am communicating directly with the HTTP API, so I will have to make some changes.  I suppose I was hoping for a way of seeing changes between the version I'm using and the current version, so I know precisely what I need to change.

To be honest, I'm not entirely sure what version I've got!  The `/info` call for me returns the same for me as the demo server currently returns, which is 0.1.0.  Is that the API version too?

**Comment by MartinaeyNL** [comment] 2023-04-03 09:58
I don't think we update that API version value. I should ask @richturner for this.
If you're running the OpenRemote Manager within docker, you can always compare the docker image ID.

**Comment by richturner** [comment] 2023-04-03 10:21
The '/info' version is related to the health status API really and isn't intended to be a version indicator for the whole HTTP API

**Comment by rmwiseman** [comment] 2023-04-03 10:32
> If you're running the OpenRemote Manager within docker, you can always compare the docker image ID.

I was looking at Docker Hub to see if the image ID is shown there, but it doesn't look like it is.  On my local installation, the output of `docker image inspect openremote/manager` includes `"Id": "sha256:65032e567be2fe3afcacff1bf3ced21bad223356e2127a632d5c42730f105f6f"`, if that's any help.  I just don't know what to compare it with!

**Comment by rmwiseman** [comment] 2023-04-03 10:32
> '/info' version is related to the health status API

Thanks for the clarification.

**Comment by rmwiseman** [comment] 2023-04-03 11:29
OK, I've got the latest version of **openremote/manager** and **openremote/postgresql** (the other two didn't need updating).  I can see that the API has changed for `POST ​/asset​/datapoint​/{assetId}​/attribute​/{attributeName}`.

It's not clear how I should use it to get the latest value of an attribute, though.  The example JSON to POST in the Swagger is:

```json
{
  "fromTimestamp": 0,
  "toTimestamp": 0,
  "fromTime": "2023-04-03T11:14:13.220Z",
  "toTime": "2023-04-03T11:14:13.220Z",
  "type": "string"
}
```

So it seems I need to supply times to indicate a range.  The trouble is, I don't know when the attribute will last have been set.  Also, there's a `type` parameter.  Looking at [the code](https://github.com/openremote/openremote/blob/3c477755322100cee677252fdd96b07c2073d28c/model/src/main/java/org/openremote/model/datapoint/query/AssetDatapointLTTBQuery.java), I can't see what this should be.  Indeed, it looks like there's also an `amountOfPoints` parameter but that's not shown in the Swagger.  I assume I would set that to 1, but can I omit the times to indicate I only want the latest one?  From the code, I would guess not.

Is this method not what I should be using to get the latest value of an attribute?
